BEGIN
  INSERT INTO NET_ADMIN.NETWORK_ELEMENT(NAME, TYPE, VENDOR, IP_ADDRESS) VALUES ('nn-gagar-gw1', 'router', 'cisco', '172.16.1.1');
  INSERT INTO NET_ADMIN.NETWORK_ELEMENT(NAME, TYPE, VENDOR, IP_ADDRESS) VALUES ('nn-gagar-dsw1', 'switch', 'cisco', '172.16.1.2');
  INSERT INTO NET_ADMIN.NETWORK_ELEMENT(NAME, TYPE, VENDOR, IP_ADDRESS) VALUES ('nn-gagar-asw1', 'switch', 'cisco', '172.16.1.3');
END;
/