BEGIN
   BEGIN
   EXECUTE IMMEDIATE 'CREATE USER NET_ADMIN IDENTIFIED BY test';
        EXCEPTION
            WHEN OTHERS
            THEN
                NULL;
   END;
   EXECUTE IMMEDIATE 'ALTER USER NET_ADMIN QUOTA UNLIMITED on SYSTEM';
   EXECUTE IMMEDIATE 'ALTER USER NET_ADMIN QUOTA UNLIMITED on USERS';
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO NET_ADMIN';
   EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO NET_ADMIN';
END;
/
